<?php
#para receber uma informação do formulario
#ultilizamos o metodo $_POST do php
$nomeProduto = $_POST["nomeRelogio"];
$marca = $_POST["marca"];
$garantia = $_POST["garantia"];
$preco = $_POST["preco"];
$precoVenda = $_POST["precoVenda"];
$quantidade = $_POST["quantidade"];
$fornecedor = $_POST["fornecedor"];
$modelo = $_POST["modelo"];
$material = $_POST["material"];
$genero = $_POST["genero"];
$codigo = $_POST["codigo"];
$tamanho = $_POST["tamanho"];
$resistencia = $_POST["resistencia"];
$parcelamento = $_POST["parcelamento"];
$imagem = $_POST["imagem"];
$fabricacao = $_POST["fabricacao"];
echo $id;
echo "</br>";
echo "</br>";
echo $nomeRelogio;
echo "</br>";
echo "</br>";
echo $marca;
echo "</br>";
echo "</br>";
echo $garantia;
echo "</br>";
echo "</br>";
echo $preco;
echo "</br>";
echo "</br>";
echo $precoVenda;
echo "</br>";
echo "</br>";
echo $quantidade;
echo "</br>";
echo "</br>";
echo $fornecedor;
echo "</br>";
echo "</br>";
echo $modelo;
echo "</br>";
echo "</br>";
echo $material;
echo "</br>";
echo "</br>";
echo $genero;
echo "</br>";
echo "</br>";
echo $codigo;
echo "</br>";
echo "</br>";
echo $tamanho;
echo "</br>";
echo "</br>";
echo $resistencia;
echo "</br>";
echo "</br>";
echo $parcelamento;
echo "</br>";
echo "</br>";
echo $imagem;
echo "</br>";
echo "</br>";
echo $fabricacao;

?>